# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2018-11-10 06:36
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0005_song_audio_file'),
    ]

    operations = [
        migrations.AddField(
            model_name='song',
            name='video',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='song',
            name='audio_file',
            field=models.FileField(blank=True, max_length=10000, null=True, upload_to=''),
        ),
    ]
